### PR TITLE
WIP: Added support for Apple Silicon

### PR DESCRIPTION
**Pull request by hpux735**
This is a work-in-progress merge that adds support for Apple Silicon (M1).

The outstanding issues are that I can't find the original source for the DiffPatchMatch code that contains word and line diffs to compile for M1.  I compiled the latest of that repo with out those methods and disabled the modes in the UI.  Finally, Shortcut Recorder is somehow a binary image in Carthage, which only includes the x86 binary.  I don't know anything about Carthage, but it builds just fine with M1.   If there's some way to tell Carthage to build instead of using a binary, I'm sure it'll work fine.

### CODE REVIEW

**Comment by dourgulf** [comment]
this merge changed bundle ID!!!

**Comment by hpux735** [comment]
It's also WIP.  When it's ready for merge, I'll check out the Xcode project from the master so there are no changes.

**Comment by trungdq88** [comment]
Hi there, thanks for the work.

It looks like all the changes belong to third party code. Sparkle framework already updated their library for M1, I just need to update it. As for the diff-patch-match, I'll check this again to see if it worth it to maintain an M1-compatible fork from Google's repo (the repo is unmaintained last time I check).

**Comment by hpux735** [comment]
Yah, I had trouble with the google repo.  The newest one I could find worked, but it didn't have the diff by word and character, so I had disable those controls.

**Comment by trungdq88** [comment]
Turns out you can just rebuild the DiffMatchPatch framework with a higher macOS target, it will build successfully for M1 with no issue.

As for Sparkle, I just update it to version 1.24, which also supports M1.

I'm gonna close this issue. There is a new beta build if you want to try out DevUtils with M1 support: version 1.8.0-beta1, opt-in via the "Preferences..." panel in the app.

Thanks for your contribution anyway 😄

**Pull request closed without merging**
